[BROKEN] fix the regression from #77820
This currently breaks, see
https://github.com/rust-lang/rust/pull/77820#discussion_r523764303.

```
DEBUG rustdoc::clean::inline build_impl: impl Some(DefId(1:7424 ~ std[7f8a]::os::linux::fs::MetadataExt)) for Some(DefId(1:7039 ~ std[7f8a]::fs::Metadata))
DEBUG rustdoc::clean::types name=None, def_id=DefId(1:7442 ~ std[7f8a]::os::linux::fs::{impl#0})
thread 'rustc' panicked at 'only local items can have restricted visibility (while calculating vis of DefId(1:7420 ~ std[7f8a]::os::linux::fs))', src/librustdoc/clean/mod.rs:1762:51
```

```
stack backtrace:
   0: rust_begin_unwind
   1: std::panicking::begin_panic_fmt
   2: rustdoc::clean::ty_visibility::{{closure}}
   3: rustdoc::clean::ty_visibility
   4: rustdoc::clean::types::Item::from_def_id_and_parts
   5: rustdoc::clean::inline::build_impl
   6: rustc_session::utils::<impl rustc_session::session::Session>::time
   7: rustdoc::passes::collect_trait_impls::collect_trait_impls
   8: rustc_session::utils::<impl rustc_session::session::Session>::time
   9: rustdoc::core::run_global_ctxt
  10: rustc_interface::passes::QueryContext::enter
  11: rustc_session::utils::<impl rustc_session::session::Session>::time
  12: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  13: rustc_span::with_source_map
  14: rustc_interface::interface::create_compiler_and_run
  15: rustdoc::core::run_core
  16: rustdoc::main_options
  17: scoped_tls::ScopedKey<T>::set
  18: rustc_span::with_session_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```