Fix `x.py check` for download-stage1
Previously, it would error out:

```
Checking compiler artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
    Checking cfg-if v0.1.10
   Compiling autocfg v1.0.0
   Compiling libc v0.2.79
   Compiling proc-macro2 v1.0.19
error[E0464]: multiple matching crates for `std`
  |
  = note: candidates:
          crate `std`: /home/joshua/src/rust/rust/build/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-25c6acf8063a3802.so
          /home/joshua/src/rust/rust/build/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-25c6acf8063a3802.rlib
```

and the error would persist past `x.py check`:

```
   Compiling bootstrap v0.0.0 (/home/joshua/src/rust/rust/src/bootstrap)
error[E0464]: multiple matching crates for `std`
  |
  = note: candidates:
          crate `std`: /home/joshua/src/rust/rust/build/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-25c6acf8063a3802.rlib
```

I think the issue was that bootstrap was adding the check metadata to
the sysroot, so that it could check `libtest`; that ended up having two
different versions of libstd in sysroot. Now the metadata is added to
stage1 instead, which avoids the duplicate version.

Additionally, this doesn't check rustc artifacts when `download-stage1`
is set; it takes a relatively long time and the `compiler/` directory
shouldn't have changes anyway.